### ISSUE TITLE
unsupported operand in main0.py on line 844

### ISSUE THREAD

**Issue by nyxdis** [seikur0/PGO-mapscan-opt#114]
I'm getting this error:

>   File "main0.py", line 844, in run
>     if (actT-curT) < (actT - all_sort[indx_sort][0]) % 3600000 < (spawn['phasetime'] - spawn['pausetime'] - 5) \* 60000:
> TypeError: unsupported operand type(s) for -: 'int' and 'list'

I've added some print statements before that line, so I know which of these operations fails and it's `spawn['pausetime']` that has a value of `[False, False, True, True]` which obviously cannot be substracted from `spawn['phasetime']` (value 60)

**Comment by seikur0** [comment]
Check the entry for that. Print spawn['id'] and look it up in your learning file.

**Comment by nyxdis** [comment]
This is (one of) the offending spawn:
`{
   "pausetime": [
    false,
    false,
    true,
    true
   ],
   "spawntime": 17.807583332061768,
   "pauses": 2,
   "lat": 54.799295880830456,
   "lng": 9.49418753119872,
   "phasetime": 60,
   "type": 1,
   "id": 4927202287617
  },
`
There are several spawns with such a pausetime.

**Comment by seikur0** [comment]
Seems like a 1x30 spawn, but pauses are 2, so it must have skipped the scan one time, because it got an empty cell twice in a row. Too many workers/too large area/too large interval.

**Comment by seikur0** [comment]
I changed it, so that not fully classified points, type 1, will be ignored in the scan as well.

**Comment by nyxdis** [comment]
I left area and interval at default values (range 30 and scaninterval 900), using 18 workers. Should I reduce any of that?

**Comment by seikur0** [comment]
Yeah definitely!!! 18 workers for range 30 are not enough for the learning phase. You see the time it takes after each run, if it's over 720 s, you need more workers. That or reduce your range. For 18 workers maybe range 15 or something.

**Comment by nyxdis** [comment]
Ok, will add more workers. Maybe you could add a hint in the README? I was always wondering how many I'd need for the learning phase and after.

**Comment by nyxdis** [comment]
Looks like this needs to be fixed here too:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "main0.py", line 1221, in run
    mod_tth = int((mod_phasetime - spawn['pausetime']) * 60000 - finished_ms)
TypeError: unsupported operand type(s) for -: 'int' and 'list'
```

**Comment by seikur0** [comment]
This should be fixed in the newest version.

Also there already is a hint in the readme, "during that time the scan interval should stay below 10 minutes, below 15 minutes may work too, no guarantee though". That tells you, that you need enough workers to stay below that interval during the learning phase.

And afterwards in the iscan, it'll show you, how many seconds you are behind, if it's increasing, you need more workers.

**Comment by nyxdis** [comment]
> This should be fixed in the newest version.

Still happens during catchup phase (note: it's line 1221, not 844)

> Also there already is a hint in the readme, "during that time the scan interval should stay below 10 
> minutes, below 15 minutes may work too, no guarantee though". That tells you, that you need enough workers to stay below that interval during the learning phase.

Ah, I see, thought that part was about the interval setting, not about scan time.
