### ISSUE TITLE
Error starting pokesite.py

### ISSUE THREAD

**Issue by FrozenSocket** [seikur0/PGO-mapscan-opt#176]
Traceback (most recent call last):
  File "pokesite.py", line 142, in <module>
    server_start()
  File "pokesite.py", line 43, in server_start
    if allsettings['icon_set'] == 'standard':
KeyError: 'icon_set'

**Comment by FrozenSocket** [comment]
fixed adding **"icon_set": "standard",** to the usersettings file

Adding your defaults with setdefault to the code would let us users only need to add stuff we'd like to change to the usersettings file. Simplifying setup for newer users? But seeing everything is also very helpful; maybe do both lol.

**Comment by UmbaSimpy** [comment]
Where exactly did you add it?
i'm new to programming and getting syntax error

"_comment6": "Pokemon with these ids won't be shown in the map. (data still gets collected)",
  "exclude_ids": [10,11,13,14,16,17,19,21,41,96],

  "_comment7": "Will scale icons by this factor.",
  "icon_scalefactor": 1.0,

  "_comment8": "Will scale the whole user interface by this factor.",
  "mobile_scalefactor": 0.7,

  "icon_set": "standard"

  "_comment9": "Notification settings. Put ids of pokemon you want to be notified about into push_ids.",
  "notifications":

EDIT: forgot the comma, im dumb

**Comment by FrozenSocket** [comment]
{
  "icon_set": "standard",

  "_comment1": "Language, can be german/english",
  "language": "english",

You were missing the comma ^^

**Comment by seikur0** [comment]
^^
